### ISSUE TITLE
Haplotype clustering plot is blank, caused by progress 

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#373] opened 2023-03-28 11:58 UTC
![image](https://user-images.githubusercontent.com/703554/228228733-4cda1589-9277-448a-a6f8-f638eaca226c.png)

Workaround:

```python
ag3 = malariagen_data.Ag3(show_progress=False)
```

Must be an interaction between tqdm and plotly.

**Comment by alimanfoo** [comment] 2023-03-28 12:02
Observed in colab.

**Comment by alimanfoo** [comment] 2023-03-28 12:31
Seems to appear with plotly 5.12 and later. Installing 5.11 works as expected.

**Comment by alimanfoo** [comment] 2023-03-28 12:50
Raised upstream: https://github.com/plotly/plotly.py/issues/4127

**Comment by leehart** [comment] 2024-07-29 14:23
gvwilson at Plotly self-assigned this a few weeks ago. 🤞

**Comment by leehart** [comment] 2024-09-19 16:44
Although this has been labelled as a bug upstream, unfortunately it has also been labelled as "not needed for current cycle", which appears to be the lowest priority (P3) as opposed to P1 "needs immediate attention" and P2 "needed for current cycle".

**Comment by leehart** [comment] 2024-10-11 08:59
Potential solution, from comment on upstream issue: https://colab.research.google.com/drive/1M9x3cG2z-Q6rhwD2yxFGZtbrKEd5oEMa?usp=sharing

Try using `from tqdm import tqdm` instead of `from tqdm.auto import tqdm` ?

**Comment by leehart** [comment] 2024-10-14 17:23
Cannot currently reproduce on Colab, which gets malariagen_data version `13.3.0` and plotly version `5.24.1`.

Using `from tqdm import tqdm` instead of `from tqdm.auto import tqdm` didn't appear to have any side-effects when I tried it locally, but that might now be unnecessary.

Closing this as not planned, since it looks unreproducible with the latest Colab, or local tests, and appears to be resolved by a later version of plotly, e.g. `5.24.1`.

If this problem resurfaces, we can re-open this issue, or open a new one, preferably with the context and environment details, to re-investigate. (The plotly issue upstream is still open.)

**Closed by leehart** 2024-10-14 17:23 UTC
Labels: bug
